### ISSUE TITLE
Notification of fork

### ISSUE THREAD

**Issue by ctrlcctrlv** [yeslogic/glyph-names#4]
Besides #2 and #3 I made many major breaking changes that are likely to be controversial but you may cherry-pick them if you wish. :-)

https://crates.io/crates/glifnames

Among them:
- https://github.com/MFEK/glifnames.rlib/commit/bfc76c0c178bdaeade860e409f3d3ec1f2fce051 (support for Legacy Adobe Glyph NL)
- https://github.com/MFEK/glifnames.rlib/commit/d2898f5865ec693b3969da5711274764d20c2fd7 (support for Zapf Dingbats)
- Added an important trait:
    ```rust
    /// Trait to implement returning a vector on your own glyph lists, required by [`GlyphName`]
    pub trait GlyphNameVec<'a> {
        /// Look up [`AsRef<str>`], return glyph name if available.
        fn glyph_name_vec<'b, S: AsRef<[char]>>(s: S) -> Option<Cow<'a, str>>;
    }
    ```
- Made it possible to always get a glyph name (.invalid.16X: https://github.com/MFEK/glifnames.rlib/blob/272f4fd2a858d3aa26aeb2fddcfe7e83d5042162/src/deterministic.rs#L18)
- Redid API. Incompatible! https://github.com/MFEK/glifnames.rlib/commit/5dccf121d2604ee44c152a7b5eb6b188a9bdd40a

**Comment by wezm** [comment]
Thanks for the head up. I'll close this now.
